### ISSUE TITLE
realm+and+return_to+do+not+match

### ISSUE THREAD

**Issue by ghost** [cpancake/steam-login#11]
![screenshot_1](https://cloud.githubusercontent.com/assets/19779985/23764905/dda6c6ce-0507-11e7-83e8-77993b9f6bac.png)

Have this issue then login. And nothing happens

**Comment by dialupnoises** [comment]
What are your realm and verify settings?

**Comment by ghost** [comment]
no i only do login , after login from steam is redirected to this page

**Comment by dialupnoises** [comment]
I mean your configuration when you added the middleware. In the example, this looks like:
```
app.use(steam.middleware({
    realm: 'http://localhost:3000/', 
    verify: 'http://localhost:3000/verify',
    apiKey: process.argv[2]}
));
```
What are your settings? I don't need to know the API key so you can redact that.

**Comment by ghost** [comment]
// Steam API
app.use(steamlogin.middleware({
    realm: '' + Config.config.steam.domain + '/steam',
    verify: '' + Config.config.steam.domain + '/verify',
    apiKey: process.argv[2]
}));

**Comment by dialupnoises** [comment]
Try only passing `Config.config.steam.domain` as the realm option.

**Comment by ghost** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/19779985/23848946/0d58570c-07e2-11e7-8648-032b038d8f44.png)

**Comment by dialupnoises** [comment]
Could you post the entire error? You've cut off the part that points to this library.

**Comment by dialupnoises** [comment]
Unless you have any other updates to this, I'm going to close the issue.
