### ISSUE TITLE
detecting a shared family account

### ISSUE THREAD

**Issue by BladeSe7en** [cpancake/steam-login#22]
This is not an issue with this NPM package, more so an issue with Steam its self. On my application, recently I have been having a problem with some people smurfing (banned players creating fake accounts to come back to our server for the sole purpose of trolling). I use steam-login to verify all my users, however I have discovered that banned players are just creating a new steam account and then using the family share to spoof as a new player.
Does anyone know how to detect if an account is being shared so I can end this constant game of Wak-A-Mole banning fake accounts?

**Comment by dialupnoises** [comment]
You might be able to use the Steam API to look up what games a user owns and check to see if they actually own the given game. I haven't looked into it - it's kinda beyond the scope of this package, and I'm not maintaining this package anymore anyways.
