### ISSUE TITLE
Unexpected weird cookie

### ISSUE THREAD

**Issue by bulgakovk** [cpancake/steam-login#4]
Hello, first of all thanks for providing this lib. I've got question regarding one weird cookie-file which I got after login via steam. Here're it is: 
![2016-04-16 17 59 55](https://cloud.githubusercontent.com/assets/8983736/14581742/23d36268-03fd-11e6-8c88-28c610e67067.png)

I have this code also:

```
app.use(require('express-session')({ resave: false, saveUninitialized: false, secret: a secret' }));

app.use(steamlogin.middleware({
    realm: 'http://127.0.0.1:3000' + '/',
    verify: 'http://127.0.0.1:3000' + '/verify',
    apiKey: config.api_key}
  ));

app.get('/login', steamlogin.authenticate(), function(req, res) {
  res.redirect('/');
});

app.get('/verify', steamlogin.verify(), function(req, res) {
    var user = req.user;
    // res.cookie('Steamid', user.steamid);
    // res.cookie('Avatar', user.avatar.medium);
    // res.cookie('Username', user.username);
    var secret = config.csrf_token + user.steamid;
    var hash = crypto.createHmac('sha256', secret).digest('base64');
    res.cookie('csrf', hash);
    /*
    some code to get tradeLink and set is as cookie
   */
    res.redirect('/');
})
```

**Comment by dialupnoises** [comment]
I don't think that's from this library. I notice you commented out a bit that set a cookie in your code called "username". If you delete the cookie, does it show up again? If not, it was probably set by that line of code and hasn't expired yet.

**Comment by bulgakovk** [comment]
> I notice you commented out a bit that set a cookie in your code called "username". If you delete the cookie, does it show up again?

Yeah, I tried to change 'username' (all my cookies have lower case in start but then I changed it) for 'Username' or "ername" and got both cookies : "username" from screenshot and my own custom username cookie.

**Comment by dialupnoises** [comment]
I don't seem to be able to reproduce this. Could it be from a different library you're loading, or maybe a different project you've run in the past locally?

**Comment by bulgakovk** [comment]
> Could it be from a different library you're loading, or maybe a different project you've run in the past locally?

Sad, but no. Ok, doesn't matter - I will just use cookies with different names. Thanks anyway.
