### ISSUE TITLE
Update node-openid to v2.x

### ISSUE THREAD

**Issue by scholtzm** [cpancake/steam-login#7]
`node-openid` crashes when running on Node v6 due to query string changes.

More info:
https://github.com/havard/node-openid/issues/148

**Comment by brianbest** [comment]
just hunted down this same issue

**Comment by scholtzm** [comment]
@brianbest If you are considering to use this package, you should be aware of https://github.com/cpancake/steam-login/issues/8

**Comment by brianbest** [comment]
@scholtzm Ah, thanks for the info!
